#!/bin/sh
set -eu

container_ip=$(
    /usr/bin/podman inspect \
        --format '{{.NetworkSettings.Networks.uyuni.IPAddress}}' \
        uyuni-server
)

case "$container_ip" in
    ""|*[!0-9.]*)
        echo "Could not resolve the Uyuni container IPv4 address" >&2
        exit 1
        ;;
esac

exec /usr/lib/systemd/systemd-socket-proxyd "${container_ip}:9898"
